services:
  postgres_db:
    image: postgres:15-alpine
    container_name: bemobix_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bemobi_password_123
      POSTGRES_DB: BemobiXDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
